### ISSUE TITLE
[10.15.7] TestDisk not showing internal drive (macOS Catalina)

### ISSUE THREAD

**Issue by ThePredators** [cgsecurity/testdisk#104]
Hello,

I tried to run the command "sudo testdisk" after installing with home brew "brew install testdisk". Unfortunately it does not show my macOS HardDrive. 

Please help.

**Comment by cgsecurity** [comment]
Extract from https://www.cgsecurity.org/testdisk_doc/running.html#running-testdisk-photorec-under-macos
"If no disk is listed when running TestDisk or PhotoRec, select System Settings –> Privacy & Security –> Full Disk Access –> Use + to add Terminal ( or TestDisk and PhotoRec themself)"
