### ISSUE TITLE
Recovered files are not with their real/original filename/path.

### ISSUE THREAD

**Issue by IvanCyber** [cgsecurity/testdisk#106]
Is there any way that we can configure this, so when we recover a deleted folder or partition, we can get the exact file names and file paths as they were before the deletion?

**Comment by ellielo** [comment]
> Is there any way that we can configure this, so when we recover a deleted folder or partition, we can get the exact file names and file paths as they were before the deletion?

Did you find the answer actually?

**Comment by cgsecurity** [comment]
> I am looking for a data recovery software with non-file signature scanning support . Any ideas?

TestDisk is a data recovery software with non-file signature scanning support.
TestDisk's undelete feature is available for FAT12, FAT16, FAT32, exFAT, NTFS and ext2 filesystems.
