### ISSUE TITLE
[Feature]: Undelete files from ext4 filesystem

### ISSUE THREAD

**Issue by DUOLabs333** [cgsecurity/testdisk#108]
Testdisk can currently undelete files from FAT, exFAT, NTFS and ext2 filesystems. Is it possible to extend this to ext3 or ext4?

**Comment by cgsecurity** [comment]
When a file is deleted from an ext3 and ext4 filesystem, the location of the first block is zeroed, so TestDisk can list all filenames, deleted or not, but it's not possible to undelete them.
PhotoRec can be use to recover files with known filetypes from the free space of the filesystem and recover them but without the original filenames.
