### ISSUE TITLE
Sony Raw (.arw) support ??

### ISSUE THREAD

**Issue by kazukyakayashi** [cgsecurity/testdisk#112]
Hello, needing Photorec I just saw that it does not list Sony RAW (.arw). Did I see wrong ?  Is it planned to support the .arw format ?

![qphotorec_win_bC9MZLopX7](https://user-images.githubusercontent.com/39823221/147390670-de24aeab-fcf4-4d41-b56d-e7f67a246f4f.png)

**Comment by cgsecurity** [comment]
arw files are part of the TIFF family.
