### ISSUE TITLE
make fails with --enable-ncmouse

### ISSUE THREAD

**Issue by Mad-Mason** [cgsecurity/testdisk#118]
OS: Slackware Linux x86_64
Kernel: 5.16.14
GCC: 11.2.0
Source: https://www.cgsecurity.org/testdisk-7.2-WIP.tar.bz2

Running `./configure --enable-ncmouse` and `make` results in

`askloc.c: In function ‘ask_location’:
askloc.c:322:9: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
  322 |         line_directory=aff_txt(2, window, msg, src_dir);
      |         ^~~~~~~~~~~~~~
askloc.c:425:29: error: expected expression before ‘>’ token
  425 |                 if(event.y => line_base - 1 && event.y < old_LINES)
      |                             ^
askloc.c:442:28: error: assignment of read-only variable ‘command’
  442 |                     command=KEY_ENTER;
      |                            ^
make[2]: *** [Makefile:2218: askloc.o] Error 1
make[2]: Leaving directory '/home/users/iain/Package_Building/testdisk/testdisk-7.2/src'
make[1]: *** [Makefile:448: all-recursive] Error 1
make[1]: Leaving directory '/home/users/iain/Package_Building/testdisk/testdisk-7.2'
make: *** [Makefile:387: all] Error 2`

**Comment by cgsecurity** [comment]
I am thinking about dropping this option as it has been broken for quite some time and for people wanting to use a mouse, it's easier to use qphotorec than photorec.
Please let me know if you really want to keep this option, in this case, I will fix the compilation problem, otherwise I will drop the code.

**Comment by Mad-Mason** [comment]
Thanks for the quick reply. I don't need the mouse support so feel free to drop the code and `configure` option.

Thanks
Iain
