### ISSUE TITLE
Drive not showing up on MacOS M1

### ISSUE THREAD

**Issue by Eleveres** [cgsecurity/testdisk#123]
The only disk listed is /dev/rdisk1. The main hard drive is not showing up. 
I'm running BigSur and installed test disk via brew.

**Comment by cgsecurity** [comment]
Choose "Sudo" in the menu.

**Comment by edmund2018** [comment]
Go to System Settings --> Privacy & Security --> Full Disk Access --> Enable for "Terminal"
