### ISSUE TITLE
How to access android root filesystem?

### ISSUE THREAD

**Issue by artivision** [cgsecurity/testdisk#127]
Good day i'm trying to undelete some Sms. On Linux via Usb Mass Storage, Testdisk finds a lot of directories but not the root ones aka DATA. What can be done? Can Testdisk work with ADB?

**Comment by cgsecurity** [comment]
A google search lists by example
https://android.stackexchange.com/questions/219346/how-to-pull-data-from-internal-memory-on-an-unrooted-phone
