### ISSUE TITLE
TestDisk closed unexpectedly during log-out

### ISSUE THREAD

**Issue by Bushido1** [cgsecurity/testdisk#128]
I use Ubuntu 22.04.1 LTS 64-bit and GNOME Terminal Version 3.44.0 for GNOME 42.
I left the deep scan on. Ubuntu logged out automatically. After log-in, terminal was closed.
I have attached the log.
[testdisk.log](https://github.com/cgsecurity/testdisk/files/10332446/testdisk.log)

**Comment by cgsecurity** [comment]
The log file contains read error messages. You should clone the disk to a new empty disk using ddrescue as explained in https://www.cgsecurity.org/testdisk.pdf

**Comment by cgsecurity** [comment]
You really need another disk as the current disk contains bad sector, a physical problem that can not be fixed.
In the meantime, you can always use TestDisk to try to copy the files you want (TestDisk, Advanced, List...)

**Comment by Bushido1** [comment]
By copying and cloning you mean I cannot recover the deleted files? I 
can just back-up the undeleted files?
Best Regards,
Olav

**Comment by Bushido1** [comment]
> You really need another disk as the current disk contains bad sector, a physical problem that can not be fixed. In the meantime, you can always use TestDisk to try to copy the files you want (TestDisk, Advanced, List...)

How long I can use a disk containing bad sector(s)?

**Comment by cgsecurity** [comment]
Cloning will copy both deleted and non-deleted data. So if there are few bad sectors, you should be able to recover both deleted and non-deleted files.
A bad sector can not be corrected.
Reinstalling or changing OS will at best hide the problem for a moment.

**Comment by Bushido1** [comment]
Does cloning copies the bad sector to the healthy disk?

**Comment by cgsecurity** [comment]
By definition, bad sectors are sectors that failed to be read. So a bad sector can not be copied.
When cloning a disk to a healthy disk, the destination disk will remain healthy.
There is no way to recreate the missing content (content that was stored in the sector that now failed to be read), so if the file that was using this sector is "recovered", it will be damaged/corrupted.
