### ISSUE TITLE
ZOOM file extension

### ISSUE THREAD

**Issue by orcutt989** [cgsecurity/testdisk#135]
Please add support in PhotoRec for `.zoom` file extension. Thanks.

https://www.cgsecurity.org/photorec/scan.php?file=f7db798860465ef49fb530f7d8fb459d6fe924a6ea6ed39a430c0f41fb62da75

**Comment by cgsecurity** [comment]
Can you provide at least 3 file samples ?

**Comment by orcutt989** [comment]
> Can you provide at least 3 file samples ?

Wow that was a fast reply! Here are 3 unconverted zoom meetings I zipped up.

https://www.mediafire.com/file/463emaqm1kfvwpt/Archive.zip/file

The files in each dir that are of interest are `double_click_to_convert_01.zoom` and `double_click_to_convert_02.zoom`

**Comment by cgsecurity** [comment]
Can you put a photorec.sig file  with the content
`
zoom 0 0x58f1052c
`
and try photorec to recover your zoom files ?

See https://www.cgsecurity.org/testdisk_doc/photorec_custom_signature.html#file-location

**Comment by orcutt989** [comment]
That works with fidentidy but I wasnt able to recover any files. I figure if fidentidy can see it then its a data recovery problem rather than a photorec problem.
