### ISSUE TITLE
Does TestDisk support apfs?

### ISSUE THREAD

**Issue by flyotlin** [cgsecurity/testdisk#138]
As per title, does TestDisk support apfs?

I know from the [documentation](https://www.cgsecurity.org/wiki/TestDisk) on the website, TestDisk doesn't support apfs.
But I saw [apfs implementation](https://github.com/cgsecurity/testdisk/blob/master/src/apfs.h) from the source code.

Does this mean I can build the code myself and get TestDisk binary that supports apfs?

PS. I want to use TestDisk on my corrupt apfs external drive to recover data on it, because `fsck_apfs` said **fsroot tree** is corrupted.

**Comment by Tarek-Hasan** [comment]
From version 7.2 release, TestDisk supports APFS partition.

**Comment by cgsecurity** [comment]
TestDisk can recover deleted APFS partition (Assuming SSD trim operation didn't discard all information) and PhotoRec can recover data from APFS filesystem.
TestDisk can't repair corrupted APFS fsroot tree.
