### ISSUE TITLE
Tell testdisk from which sector to start

### ISSUE THREAD

**Issue by killuadk** [cgsecurity/testdisk#140]
I using Testdisk 7.0 to recover 2 partition 
From what i test i can only find the 2 partition when i select "None partition table"
I can even list my files &folder
But After hours of scanning when i press continue it tell me that i can't write partition that i found because i did select No e in the first place so there is no partition table to write in it 
I did take photo for the start & end sector now i need to repeat scan but is there way to tell testdisk to start from X sector so it will find my partition faster

**Comment by cgsecurity** [comment]
You can choose Stop in Quick Search and next choose Deeper Search.
If you know where the partition is, after Quick Search or Deeper Search (Choose Stop to avor the partition search if you want), you can use 'a' to manually add the partition.

In Deeper Search, you can use 'F' (Uppercase) to continue the scan after the end of the first partition ending after the current location. Usually it's a good idea only if you know that the partition already found by TestDisk is correct.

**Comment by Artoria2e5** [comment]
Huh… I really wish I could just enter a range to look in. In my particular case, a malfunctioning hard drive enclosure decided to wipe some head part of my disk, but there seems to be some data at the tail end. I know the disk is a default macOS format: 200 MB(without i) EFI part followed by the rest being just HFS+, but the head superblock is clearly gone. If only I could tell testdisk to only look for the tail one…

**Comment by cgsecurity** [comment]
I have uploaded a new 7.2-WIP version (code not yet committed on github). Can you try it ?
When searching for a partition, press the key "+" each time you want to skip 5% of the disk.
