### ISSUE TITLE
cross compile windows application

### ISSUE THREAD

**Issue by qiankl** [cgsecurity/testdisk#141]
I am trying to compile windows applications but encountered with some difficulties.

I see some information from the document that it could be cross compiled on Fedora and offerred some tools. I have prepared all the environment in docker container, but I don't know how to use. Could you please show me some instructions? Thanks!

**Comment by cgsecurity** [comment]
Here are the RPM spec files use to compile TestDisk & PhotoRec for Windows
https://github.com/cgsecurity/testdisk/blob/master/cygwin-testdisk-copr.spec
https://github.com/cgsecurity/testdisk/blob/master/mingw-testdisk-copr.spec

Some dependencies can be found already compiled at
https://copr.fedorainfracloud.org/coprs/grenier/cygwin-testdisk/packages/
https://copr.fedorainfracloud.org/coprs/grenier/mingw-testdisk/packages/

**Comment by qiankl** [comment]
Great. Thanks a lot!
