### ISSUE TITLE
Hello Master,How to compile win_qphotorec ?

### ISSUE THREAD

**Issue by basicbh** [cgsecurity/testdisk#164]
I can compile  the DOS UI qphotorec.exe  by cygwin,but How to compile win_qphotorec.exe ?
What do I need?

Thanks!

**Comment by JonnyTech** [comment]
https://raw.githubusercontent.com/cgsecurity/testdisk/refs/heads/master/INSTALL

**Comment by basicbh** [comment]
> https://raw.githubusercontent.com/cgsecurity/testdisk/refs/heads/master/INSTALL

thank you,but I mean I want to compile the **qphotorec_win.exe**  with windows UI not DOS UI.

**Comment by basicbh** [comment]
Compilation environnement
=========================
testdisk uses several libraries if available:

 * libncurses - Required, TestDisk and PhotoRec use a text user interface, Ncurses library and development files must be available.
 * Ext2fs library - Optional, used by TestDisk to list files from ext2/ext3/ext4 partition and by PhotoRec to be able to carve the free space from an ext2/ext3 partition instead of the whole partition
 * EWF library - Optional, TestDisk and PhotoRec use it to access Expert Witness Compression Format files (ie Encase files)
 * Iconv - Optional, used to handle unicode filenames
 * Jpeg library - Optional, used by PhotoRec to improved JPEG recovery rate
 * NTFS library - Optional, used by TestDisk to list files from NTFS partition
 * Reiserfs library - Optional, used by TestDisk to list files from reiserfs partition
 * zlib library - Optional, used by PhotoRec to decompress gzipped content
 *** Qt5 library - Optional, required for QPhotoRec and to update the configure script.**

**Comment by basicbh** [comment]
still need help,thanks everyone!

**Comment by basicbh** [comment]
**./configure --enable-qt=yes**  Im using this command,then I got a qphotorec.exe 
![QQ图片20241027231504](https://github.com/user-attachments/assets/964a91d0-7ef4-475d-8cd9-bf7218e9c5ad)

but cant run,I put it in E:\cygwin64\bin show nothing,but the **testdisk.exe IS WELL.**
