### ISSUE TITLE
old install instructions

### ISSUE THREAD

**Issue by johndoe71rus** [cgsecurity/testdisk#22]
Please update install/compile instructions.

./configure not found

**Comment by cgsecurity** [comment]
Done, the INSTALL file has been updated.

**Comment by cgsecurity** [comment]
To summarize, the INSTALL file say to run:

```
mkdir config
autoreconf --install -W all -I config
./configure
make
```

Is it ok or not ?

**Comment by johndoe71rus** [comment]
autoreconf --install -W all -I config
configure.ac:317: installing 'config/compile'
configure.ac:13: installing 'config/config.guess'
configure.ac:13: installing 'config/config.sub'
configure.ac:17: installing 'config/install-sh'
configure.ac:17: installing 'config/missing'
src/Makefile.am:396: warning: <F: non-POSIX variable name
src/Makefile.am:415: warning: '%'-style pattern rules are a GNU make extension
src/Makefile.am: installing 'config/depcomp'

this  warning is ok?

**Comment by cgsecurity** [comment]
Yes, it's a warning, not an error.

**Comment by johndoe71rus** [comment]
this second run make, so not full log 

~/Programs/testdisk$ make
make  all-recursive
make[1]: Entering directory `/home/johndoe/Programs/testdisk'
Making all in icons
make[2]: Entering directory `/home/johndoe/Programs/testdisk/icons'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/johndoe/Programs/testdisk/icons'
Making all in man
make[2]: Entering directory `/home/johndoe/Programs/testdisk/man'
Making all in zh_CN
make[3]: Entering directory `/home/johndoe/Programs/testdisk/man/zh_CN'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/johndoe/Programs/testdisk/man/zh_CN'
make[3]: Entering directory `/home/johndoe/Programs/testdisk/man'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/johndoe/Programs/testdisk/man'
make[2]: Leaving directory `/home/johndoe/Programs/testdisk/man'
Making all in src
make[2]: Entering directory `/home/johndoe/Programs/testdisk/src'
/bin/mkdir -p lang
  GEN      lang/qphotorec.ca.qm
lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease': No such file or directory
make[2]: *** [lang/qphotorec.ca.qm] Error 1
make[2]: Leaving directory `/home/johndoe/Programs/testdisk/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/johndoe/Programs/testdisk'
make: *** [all] Error 2

**Comment by johndoe71rus** [comment]
for lang/qphotorec.ca.qm lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease': No such file or directory need 
sudo apt-get install qttools5-dev-tools

but now i stop this http://paste.ubuntu.com/24320337/

ln -s qphotorec_locale.qrc . || exit 0
ln: failed to create symbolic link ‘./qphotorec_locale.qrc’: File exists

**Comment by cgsecurity** [comment]
"exit 0" is used to ignore the potential error from ln.
The compilation is ok, all the binaries have been compiled.
