### ISSUE TITLE
Analysis hangs forever after first cylinders

### ISSUE THREAD

**Issue by mirh** [cgsecurity/testdisk#23]
[logs](https://github.com/cgsecurity/testdisk/files/925771/logs.gz)
I'm on W10 CU trying to scan a dynamic disk. 
Until the 350 cylinder, disk is being actually read and all. Then I still get 100% disk activity from Windows, but 0MB/s throughput. 

Besides, I'm not sure if that `filewin32_setfilepointer(\\.\G:)` function is even supposed to be there, since I have no G:\ disk attached in the first place.

**Comment by mirh** [comment]
Still a problem.

**Comment by cgsecurity** [comment]
AFAIK it's an hardware or windows problems...

**Comment by mirh** [comment]
Ehrm.. Anything more I can look into?

**Comment by cgsecurity** [comment]
You should clone the disk to a new empty one using ddrescue.
See chapters "DDRescue: data recovery from damaged disk" and "Creating a live USB" in https://www.cgsecurity.org/testdisk.pdf

**Comment by mirh** [comment]
The disk is perfectly functional and working, this is why I'm kind baffled by this odd breakage.

**Comment by cgsecurity** [comment]
Do you have this problem if you try the Linux version ?
If necessary, see https://www.cgsecurity.org/testdisk.pdf on how to create a Linux Live USB.

**Comment by Scripter17** [comment]
Currently getting the same issue on Ubuntu 22.04

**Comment by mirh** [comment]
Even pretending you really had the same issue, especially since you are on linux you should have attached a log from there.

**Comment by Scripter17** [comment]
1. ...You're right I really should've. Sorry
2. I don't even remember which drive it is. If I can I'll see if I can try again and get a log from that
