### ISSUE TITLE
[Photorec] Wrong estimated time to completion (ETA)?

### ISSUE THREAD

**Issue by pabloab** [cgsecurity/testdisk#27]
Like [this guy on Askubuntu](https://askubuntu.com/questions/885921/will-it-take-3-years-to-recover-1tb-data) I'm trying to recover files from a external hard disk drive with some bad sectors:
![image](https://cloud.githubusercontent.com/assets/657836/26426900/ed937494-40b0-11e7-8af8-ec4193f2899f.png)
In my case my 1TB HDD connected with USB 3.0 will finish in... 5 years. If this is sadly true I suspect the user should receibe a warning. I also have a superfast SSD drive on my main computer, I wonder why photorec doesn't just make an image and work on the ssd.

**Comment by pabloab** [comment]
I was recommended to use `ddrescue` and work on generated disk image but before trying that alternative and after 3 hours of work photorec reach the "Recovery completed." (153 files recovered).
So probably the algorithm that calculate ETA may need some adjustments.

**Comment by cgsecurity** [comment]
The ETA will never be reliable with bad sectors as their distribution on the disk is unknown.

**Comment by pabloab** [comment]
If become so unreliable to the point it say going to take five years then probably shouldn't display it at all. This is a bug IMO.
