### ISSUE TITLE
Partition table type selection results in lost read permission

### ISSUE THREAD

**Issue by Wandang** [cgsecurity/testdisk#31]
My friend has an external hdd with different media on it. It can no longer be accessed via windows (windows wants to format the drive before being useable). The hdd is 1TB and not manually partitioned. Gparted found ~950GB unallocated memory and ~100mb metadata partition

Therefore I tried to help and flashed SystemRescueCD onto a usb drive.

After consulting the wiki I tried to follow step by step. When I needed to select a partition table type I followed through with the assumed one (Intel) because the wiki states that this would be most likely correct.

After writing this to drive I was advised to reboot by the program which I did. Thereafter I was unable to read the drive anymore. It was still shown in lsusb and /var/log/messages with its metadata and write protection was apparently off (stated in message log). But after loading the metadata it states that the drive has a input/output error and read error.

Is there any hint what could be wrong on my side? Or could this be a locked resource because of the reboot?

I just came back from my friend and unfortunately cannot provide any screenshots.

**Comment by cgsecurity** [comment]
Looks like a purely hardware problem, not a bug in testdisk or photorec.
Probably a problem mixing bad sectors and damaged head.
