### ISSUE TITLE
Request: bgzip (block based gzip) support

### ISSUE THREAD

**Issue by magicDGS** [cgsecurity/testdisk#44]
I am trying to add a custom formats to `photorec.sig` for common bioinformatic files (see http://samtools.github.io/hts-specs/ for more information on some of them), but it is quite difficult because some of the formats are compressed with bgzip (an extension of gzip based on blocks).

It looks like some compressed signatures are directly implemented in the `.gz` format (e.g., `xml.gz`) and thus a new compressed format can be added by modifying https://github.com/cgsecurity/testdisk/blob/master/src/file_gz.c
Nevertheless, this does not allow to identify any kind of file compressed (with `.gz` or other algorithm) and thus is difficult to extend. In addition, it might be difficult for users to create a `photorec.sig` for a compressed extension where the signature is a string. 

It will be nice if the `photorec.sig` can have some kind of mechanism to indicate compressed signatures with certain algorithms, or to add better extensibility of compressed formats (e.g., a boolean field for the `file_hint_t` struct to indicate that it might use first a compressed format, and then identify the signature after decompression).

Thanks in advance!

**Comment by cgsecurity** [comment]
It may be possible to use smething like "extension [-|gzip] offset magic_values".
Extending the signature format will break the existing signatures...

Currently, you have to deal with file_gz.c, example
```
diff -ruw testdisk/src/file_gz.c ../testdisk-7.1-WIP/src/file_gz.c
--- testdisk/src/file_gz.c      2018-03-22 13:20:13.628017471 +0100
+++ ../testdisk-7.1-WIP/src/file_gz.c   2018-04-10 11:22:25.121483486 +0200
@@ -177,6 +177,12 @@
     file_recovery_new->min_filesize=22;
     file_recovery_new->time=le32(gz->mtime);
     file_recovery_new->file_rename=&file_rename_gz;
+    if(memcmp(buffer_uncompr, "BAM\1", 4)==0)
+    {
+      /* https://github.com/samtools/hts-specs SAM/BAM and related high-throughput sequencing file formats */
+      file_recovery_new->extension="bam";
+      return 1;
+    }
     if(memcmp(buffer_uncompr, "PVP ", 4)==0)
     {
       /* php Video Pro */

```

**Comment by magicDGS** [comment]
Thanks @cgsecurity - maybe to keep previous signature files without breaking changes, incorporating a `photorec.compress.sig` might be an option to add compressed formats (the second field should contain a valid compression, such gzip, and maybe also others such bz2 and so on). This is quite important for bioinformatics, which most of the formats are compressed.

In addition, it looks like PhotoRec pulls out BAM files as separated `gzip`. Could it be possible to detect when several `gzip` are concatenated into a block-compressed file (`bgzip`)?

**Comment by magicDGS** [comment]
Here there are some magic patterns for bioinformatics: https://github.com/lindenb/magic/tree/master/patterns

Maybe that could be implemented in photorec (or an extension of it) to recover bioinformatics data...

**Comment by cgsecurity** [comment]
Do you mean that PhotoRec recover a single bam file as several gzip files ? If it's the case, please try to reproduce the problem with `photorec /d recup_dir /cmd sample.bam search`, if you get several gz files, please share the file sample.

**Comment by magicDGS** [comment]
Using this BAM (https://github.com/broadinstitute/gatk/blob/master/src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam) produces the following result with your command (without the fix proposed in your previous comment):

```
-rw-r--r--  1 daniel  staff    15M Apr 10 12:31 f0000000.gz
-rw-r--r--  1 daniel  staff   4.1M Apr 10 12:31 f0030938.gz
-rw-r--r--  1 daniel  staff   4.4M Apr 10 12:31 f0039252.gz
-rw-r--r--  1 daniel  staff    39M Apr 10 12:31 f0048275.gz
-rw-r--r--  1 daniel  staff   1.4M Apr 10 12:31 f0128504.gz
-rw-r--r--  1 daniel  staff   6.2M Apr 10 12:31 f0131315.gz
-rw-r--r--  1 daniel  staff   5.1M Apr 10 12:31 f0143990.gz
-rw-r--r--  1 daniel  staff   815K Apr 10 12:31 f0154341.gz
-rw-r--r--  1 daniel  staff   3.1K Apr 10 12:31 report.xml
```

With the fix for BAM files, the only difference is that the `f0000000.gz` is re-named to `f0000000.bam`.

**Comment by magicDGS** [comment]
While recovering some real case data, I am realizing that it is not only a problem with the BAM format, but also with any file compressed with bgzip.

**Comment by magicDGS** [comment]
Many thanks for looking into this. I will check your patch as soon as possible (I haven't even look into the code, because this is a quick answer). Do you have the patch in your previous comment commited to some repository (either a branch here or in the official one)? That will be useful for me to test with your changes.

In the meantime, some hints about bioinformatic formats to help you working on it:

* Answering your question: BAM, BAI and CSI are bgzip compressed files. Nevertheless, look below some problems with the indexes.
* bgzip compression is not only expected in those formats, but in other tab-delimited files - this might be important for recovering properly other bgzip files. My recommendation is to set the `bgz` extension if the file is detected to be block-compressed and not part of the supported BAM-related files.
* A recommendation for index files: there are two conventions for the name (`bam.bai` and `bai`, and `bam.csi`, `csi`, and even `cram.csi`), but I recommend to stick to the simpler one (`bai`, `csi`) to be on the safe side (a csi index might be associated not with a BAM file).

For your information and to make easier your progress here, I implemented in my fork (see the branch https://github.com/magicDGS/testdisk/tree/dgs_bioinf_files) some of the common bioinformatics formats that might be compressed. That can be a reference for your fix.

**Comment by magicDGS** [comment]
Using the patch I re-run the command for checking the CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam file, and it does not create any file, just the following report.xml:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<dfxml xmloutputversion='1.0'>
  <metadata 
  xmlns='http://www.forensicswiki.org/wiki/Category:Digital_Forensics_XML' 
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
  xmlns:dc='http://purl.org/dc/elements/1.1/'>
    <dc:type>Carve Report</dc:type>
  </metadata>
  <creator>
    <package>PhotoRec</package>
    <version>7.1-WIP</version>
    <build_environment>
      <compiler>GCC 4.2</compiler>
      <library name='libext2fs' version='none'/>
      <library name='libewf' version='none'/>
      <library name='libjpeg' version='none'/>
      <library name='libntfs' version='none'/>
      <library name='zlib' version='1.2.5'/>
    </build_environment>
    <execution_environment>
      <os_sysname>Darwin</os_sysname>
      <os_release>15.6.0</os_release>
      <os_version>Darwin Kernel Version 15.6.0: Tue Jan  9 20:12:05 PST 2018; root:xnu-3248.73.5~1/RELEASE_X86_64</os_version>
      <host>i122mc132.vu-wien.ac.at</host>
      <arch>x86_64</arch>
      <uid>502</uid>
      <start_time>2018-04-10T16:12:50+0200</start_time>
    </execution_environment>
  </creator>
  <source>
    <image_filename>/Users/daniel/workspaces/gatk_magicdgs/src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam</image_filename>
    <sectorsize>512</sectorsize>
    <image_size>79856849</image_size>
    <volume>
      <byte_runs>
        <byte_run offset='0' img_offset='0' len='79856849'/>
      </byte_runs>
    </volume>
  </source>
  <configuration>
  </configuration>
</dfxml>
```

**Comment by cgsecurity** [comment]
Can you check the dev branch ?

**Comment by magicDGS** [comment]
Sorry for my previous comment, I am running on the same computer photorec for a failing disk without getting gzip files and thus the run that I showed is picking up that configuration. Is it possible to pass a different configuration to a different photorec run?

Once I figure out how to run it without killing the process, I will check the dev branch. Thanks!

**Comment by magicDGS** [comment]
Ok, I found the way using `photorec /d recup_dir /cmd CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam fileopt,everything,enable,search`. The tests that I did:

* Using the current brew version (7.0): 
```
-rw-r--r--  1 daniel  staff    15M Apr 11 11:38 f0000000.gz
-rw-r--r--  1 daniel  staff   4.1M Apr 11 11:38 f0030938.gz
-rw-r--r--  1 daniel  staff   4.4M Apr 11 11:38 f0039252.gz
-rw-r--r--  1 daniel  staff    39M Apr 11 11:38 f0048275.gz
-rw-r--r--  1 daniel  staff   1.4M Apr 11 11:38 f0128504.gz
-rw-r--r--  1 daniel  staff   6.2M Apr 11 11:38 f0131315.gz
-rw-r--r--  1 daniel  staff   5.1M Apr 11 11:38 f0143990.gz
-rw-r--r--  1 daniel  staff   815K Apr 11 11:38 f0154341.gz
-rw-r--r--  1 daniel  staff   3.0K Apr 11 11:38 report.xml
```
* Using the patch applied to my branch (I don't know if it is the same as the dev branch):
```
-rw-r--r--  1 daniel  staff    76M Apr 11 11:39 f0000000.bam
-rw-r--r--  1 daniel  staff   1.6K Apr 11 11:39 report.xml
```
* Using the dev branch:
```
-rw-r--r--  1 daniel  staff    76M Apr 11 11:46 f0000000.bam
-rw-r--r--  1 daniel  staff   1.6K Apr 11 11:46 report.xml
```
And the MD5 is the same for all the files: 1cb7aa6facf25bb759b1e1d00dd19a3d

For testing if bgzip for a non-BAM file is also split or not, I took the BAM file, convert it to plain text using [samtools](http://www.htslib.org/doc/samtools.html) and bgzip it. The command was `samtools view -h CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam | bgzip -c > CEUTrio.HiSeq.WGS.b37.NA12878.20.21.sam.bgz`.

In this case, the result was:
* Using brew version:
```
-rw-r--r--  1 daniel  staff   6.3M Apr 11 11:49 f0000000.gz
-rw-r--r--  1 daniel  staff    16M Apr 11 11:49 f0012983.gz
-rw-r--r--  1 daniel  staff   4.9M Apr 11 11:49 f0045914.gz
-rw-r--r--  1 daniel  staff   7.6M Apr 11 11:49 f0055896.gz
-rw-r--r--  1 daniel  staff   5.1M Apr 11 11:49 f0071394.gz
-rw-r--r--  1 daniel  staff   556K Apr 11 11:49 f0081749.gz
-rw-r--r--  1 daniel  staff    11M Apr 11 11:49 f0082860.gz
-rw-r--r--  1 daniel  staff   5.6M Apr 11 11:49 f0106065.gz
-rw-r--r--  1 daniel  staff   1.4M Apr 11 11:49 f0117549.gz
-rw-r--r--  1 daniel  staff   9.7M Apr 11 11:49 f0120481.gz
-rw-r--r--  1 daniel  staff   883K Apr 11 11:49 f0140341.gz
-rw-r--r--  1 daniel  staff   216K Apr 11 11:49 f0142107.gz
-rw-r--r--  1 daniel  staff   1.9M Apr 11 11:49 f0142539.gz
-rw-r--r--  1 daniel  staff   4.0K Apr 11 11:49 report.xml
```
* Using dev branch version:
```
-rw-r--r--  1 daniel  staff    72M Apr 11 11:49 f0000000.gz
-rw-r--r--  1 daniel  staff   1.6K Apr 11 11:49 report.xml
```

So it also works for other block-compressed files where the format is not known (in your branch, BAM/BAI/CSI). Nevertheless, I recommend that the file extension used in this case is `bgz`, to show that it was detected as a block-compressed file. It will be easier for recovery, because knowing if it was detected as bgzip or gzip might help identifying files (e.g., some formats in bioinformatics are compressed with gzip, such FASTA, and other formats should **always** be compressed as bgzip).

Thanks a lot for the work done here.

**Comment by magicDGS** [comment]
Can you change https://github.com/cgsecurity/testdisk/commit/cdde95797ee04b258a7fd29fd4ebcb69f32da74b#diff-bcb8aa815b8b17b77dac79ecc7656e8eR107 to set the extension to `bgz`? I think that will be perfect (I tested that normal gzipped files are set to `gz`).

Thanks a lot for the help and the quick fix!

**Comment by cgsecurity** [comment]
Done, I have modified the extension in the dev branch.

**Comment by magicDGS** [comment]
Thank you! This software is awesome and it is great your commitment for support new formats!

Is there any plan to include the changes in the next release? And to make a new release soon?

**Comment by magicDGS** [comment]
Thanks!

**Comment by timofonic** [comment]
@cgsecurity 7.1-WIP? Does it mean a 7.1 release is coming? Thanks a lot!

**Comment by cgsecurity** [comment]
7.1 will succeed to 7.1-WIP when it will be released
