### ISSUE TITLE
Unable to set start/stop sector more than UINT_MAX on creating partition

### ISSUE THREAD

**Issue by man4red** [cgsecurity/testdisk#5]
Unable to set start/stop sector more than UINT_MAX on creating partition (4294967295)

**Comment by man4red** [comment]
OS: Win8.1 x64
Ver: testdisk 7.0 x64

**Comment by cgsecurity** [comment]
Can you check if the problem is present in latest 7.1-WIP ?
Which partition table type are you using ? EFI GPT ?

**Comment by man4red** [comment]
![Error]
(http://i.snag.gy/OqHrE.jpg)
Yes, EFI GPT
