### ISSUE TITLE
Relocate token from `.travis.yml` to a non-public place

### ISSUE THREAD

**Issue by ThisNameIsNotAllowed** [cgsecurity/testdisk#52]
It seems as if you hardcoded your token->secure to the `.travis.yml` file.
You might want to change this to a setting or some non public place.

**Comment by cgsecurity** [comment]
What I have done seems to match the documentation from https://docs.travis-ci.com/user/sonarcloud/
Is this really a problem ?

**Comment by ThisNameIsNotAllowed** [comment]
I'm fully with you, not seeing any problem in doing so.

It's just the feeling to hide such things from public places.

Personally I would go for the definition of the sonar token within the repository settings.
(https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings)
