### ISSUE TITLE
NEF file support (RAW format)

### ISSUE THREAD

**Issue by OutsourcedGuru** [cgsecurity/testdisk#55]
The Nikon SLR cameras have an [NEF format file type](https://www.nikonusa.com/en/learn-and-explore/a/products-and-innovation/nikon-electronic-format-nef.html). Is there any chance that you could add support for these files?

Thanks in advance

**Comment by cgsecurity** [comment]
Have you tried PhotoRec 7.1-WIP ? NEF is part of the TIFF file family. It should already be recovered.

**Comment by OutsourcedGuru** [comment]
Actually, yes. I downloaded and ran this exact version against a 32GB SD my girlfriend had formatted after uploading to her MacBook... and within the week her MacBook crashed. So I'm now trying to recover perhaps 600 NEF files from our Yosemite trip. The MacBook is at Apple getting a new motherboard.

PhotoRec ran through the scan, taking perhaps forty minutes. It successfully resurrected four .MOV files and a few hundred .tif files which appear to be the thumbnails (only). What's odd is that the file sizes for these "thumbnails" is around 30MB each which makes me think that all the data is there.

Renaming one of the files with an `.nef` extension doesn't seem to work: Gimp will bring it in, complain about an unexpected field and show it as a thumbnail graphic.

---

I tried perhaps four of the "free" software programs out there which turned out to be teaser-ware. They wanted to be upgraded before offering any actual files from the restoral. And yet, one of them indicated that there was a subdirectory which included `.jpg` files on the card, something that yours didn't find. In that case, their preview indicated that those were the thumbnails and the NEF files in another subfolder were the big ones.

Any thoughts?

**Comment by OutsourcedGuru** [comment]
![screen shot 2018-09-24 at 8 35 39 am](https://user-images.githubusercontent.com/15971213/45962064-defe9b80-bfd4-11e8-916d-cd00ba0803f3.png)

I did this before...
![screen shot 2018-09-24 at 8 36 23 am](https://user-images.githubusercontent.com/15971213/45962108-f63d8900-bfd4-11e8-8041-621ce182a8bf.png)

But I'll try this one this time...
![screen shot 2018-09-24 at 8 37 01 am](https://user-images.githubusercontent.com/15971213/45962151-0ce3e000-bfd5-11e8-9d28-e801b727e0bd.png)

Then this...
![screen shot 2018-09-24 at 8 37 29 am](https://user-images.githubusercontent.com/15971213/45962174-1e2cec80-bfd5-11e8-8da6-e6caa3bbb297.png)

And this...
![screen shot 2018-09-24 at 8 38 14 am](https://user-images.githubusercontent.com/15971213/45962224-38ff6100-bfd5-11e8-9133-f9ce62491ab5.png)

...and I'll let it run.

**Comment by OutsourcedGuru** [comment]
Here's an example of one of the `.tif` files that was resurrected, noting that she shoots in the raw (NEF) format on her Nikon D750.

[Link to Google Drive](https://drive.google.com/open?id=1wV6F-WXDC08PsjPRnrmYwJc71k04fndp)

Are you sure that this version of PhotoRec does NEF? I've reviewed the code and it doesn't appear to be there.

**Comment by OutsourcedGuru** [comment]
I'm now bringing the `.tif` file into Adobe Photoshop Elements using the "Open in Camera Raw" feature but at Zoom = 100% it definitely thinks this is a thumbnail.

**Comment by OutsourcedGuru** [comment]
Alright, I think I have a solution here.

* Downloaded [Nikon's ViewNX-I](https://downloadcenter.nikonimglib.com/en/download/sw/89.html) software
* Brought in the selected `.tif` file
* Saved it with maximum quality as a `.jpg`

![screen shot 2018-09-24 at 9 12 42 am](https://user-images.githubusercontent.com/15971213/45964439-a5c92a00-bfda-11e8-9346-f5a25d92415d.png)

![screen shot 2018-09-24 at 9 15 32 am](https://user-images.githubusercontent.com/15971213/45964443-abbf0b00-bfda-11e8-987d-37623635a82e.png)

This is probably the best that she could hope for. As a photographer, she's like the control that raw would have given her but this is a working compromise.  I guess I'm good here.  Thanks.

**Comment by cgsecurity** [comment]
Do you get better results if you rename the recovered .tif as .nef ?
Can you share an unmodified nef file (not a recovered one) taken with this camera ?

**Comment by OutsourcedGuru** [comment]
Actually, I renamed all of the `.tif` files in place and Nikon's ViewNX-I program had no problems whatsoever with them. All the EXIF data is there, it has the full 6Kx4K resolution and has the embedded thumbnails available.

My guess is that Nikon is repurposing the TIF standard, renaming it NEF for their own use.

Try [this link](https://drive.google.com/open?id=1wV6F-WXDC08PsjPRnrmYwJc71k04fndp), it should include two new files. Her D750 was in NEF mode; my D3200 was in JPG.

**Comment by 153957** [comment]
@cgsecurity If you still required NEF samples, or RAW samples from other cameras, check out this site for a nice collection: https://raw.pixls.us/#repo
