### ISSUE TITLE
Logging option is prompted before elevating to sudo, causing two logging prompts

### ISSUE THREAD

**Issue by wesinator** [cgsecurity/testdisk#61]
Ubuntu 18.04 Bionic
testdisk (7.0-3build2)
TestDisk 7.0
GCC 7.2

Selecting "No Log" option, logging option is asked twice.

**To reproduce:**
 - testdisk, select "No Log"
After selecting No Log, the same logging menu reappears again a second time. Selecting No Log the second time moves on to the program menu.

**Comment by cgsecurity** [comment]
I am unable to reproduce the problem with Linux 7.0 and 7.1-WIP binaries from https://www.cgsecurity.org by using the arrow keys and the enter key.
Can you check with these binaries ?

**Comment by wesinator** [comment]
I can't reproduce with those versions either.

**Comment by wesinator** [comment]
So it seems this happens when running as `testdisk` with SUDO_BIN configured. 
The program asks for logging option before elevating to sudo, then again as sudo.

**Expected:** elevate, then ask for logging option
