### ISSUE TITLE
Do not use CHS geometry on UEFI GPT disks

### ISSUE THREAD

**Issue by Googulator** [cgsecurity/testdisk#68]
GPT has no concepts corresponding to CHS disk geometry; it's exclusively LBA. I'm not aware of any GPT partitioning utility using cylinder alignment (maybe some early Itanium tools did, but encountering that is extremely unlikely; the GPT specification in fact was released long after IDE hard drives with virtual geometry became common), and have never in my practice seen anything other than power-of-2 alignment (usually 1MB) on GPT disks.

TestDisk should default to searching on megabyte boundaries on GPT disks (perhaps with an option for CHS, in case someone does come across an old Itanium HDD), and not display CHS-based messages, like "Analyse cylinder X/Y".

**Comment by cgsecurity** [comment]
TestDisk already searches on megabyte boundaries on GPT disks.
Cylinder number are shorter than LBA address in messages, it's why they are sometimes used for display.

**Comment by Googulator** [comment]
My suggestion would be to display progress in megabytes on GPT disks.
