### ISSUE TITLE
QPhotoRec: Empty window when started as root/via sudo

### ISSUE THREAD

**Issue by Quanttek** [cgsecurity/testdisk#7]
Title basically says it all. To select any of my normal drives, I would need to use qphotorec with sudo, though doing so leads to a blank window. Atleast this is the problem, installing qphotorec on a Fedora 23 live usb-stick, using the official package. No such problem exists (of course) with the command line tool photorec, which I then used. 

![screenshot from 2016-05-16 18-44-16](https://cloud.githubusercontent.com/assets/7535016/15306166/4f613c38-1b96-11e6-84b3-4bb0e454ec1a.png)

**Comment by cgsecurity** [comment]
I have been able to reproduce the problem using qphotorec-7.0-7.fc23.x86_64
Please run "dnf copr enable grenier/testdisk" and run "dnf update qphotorec". It should install latest qphotorec 7.1-WIP. Can you check that the problem is corrected ?

**Comment by Quanttek** [comment]
I can confirm, that the problem is corrected
