### ISSUE TITLE
Killed: 9

### ISSUE THREAD

**Issue by drandreaskrueger** [cgsecurity/testdisk#8]
```
bunzip2 testdisk-7.0.mac_intel.tar.bz2
tar -xf testdisk-7.0.mac_intel.tar
cp testdisk-7.0 [usbstick]
```

OS X -  El Capitane - recovery boot

```
cd [usbstick]/testdisk-7.0
./testdisk
```

results in:

```
Killed: 9
```

On my old OS X SnowLeopard, it works.

**Comment by cgsecurity** [comment]
Does "dmesg" show more information ?
If you run "ldd ./testdisk", do you see missing libraries ?

**Comment by drandreaskrueger** [comment]
Sorry, I cannot. Not my machine, and is already at the shop - to have the HD swapped for a new one. Perhaps I will soon have that broken HD on my table, to see what I can recover. 

It was during a standard CMD+R recovery boot terminal of a probably uptodate ElCapitan OS X. With a read-only file system, probably due to broken/disappeared/zeroed partition table. 

Thanks for your quick answer!

**Comment by chuckchamberland** [comment]
Just FYI, I'm seeing the same thing in the recovery environment. There is likely a missing dependency. ldd is not available in the recovery environment.

**Comment by sharq88** [comment]
Having the same problem. Any idea how to run this in recovery mode? :(

**Comment by dcownie** [comment]
I had this problem (KIlled: 9) but fixed it by pulling the testdisk sources from github and recompiling (on another mac).  This gave me a x86_64 binary while the precompiled version is just a 32bit binary x86. I thought I would have to hack the makefile to statically link but the default makefile built x86_64 binary worked fine.  (file <execuable> reports if you have an x86 or x86_64 binary). 

I moved the recompiled testdisk x86_64 binary across to my sick MacBook pro on a ~500GB USB drive (which was big enough to save the data partitions from the sick Macbook pro SSD later.)

Thanks to testdisk ! 

I managed to recover the whole data partition from my daughters Macbook pro 256GB SSD which had taken an unfortunate drive and then brief swim in the dogs water bowl... 

Downside is I still can't persuade the Mac recovery diskutil program (I can boot to this from an old time machine backup disk) to see the partition table ... and get a write error from testdisk trying to write 
back the partition table taht it has found.  

Ideas ? 

I fear the SSD is no longer writeable. (I'm waiting on the gmd5sum comparision of my 1st and 2nd reads of the data partition before I try erasing the SSD and re-partitioning ... but doubt that will work)

**Comment by akram** [comment]
Hi @dcownie, 


can you put this build version somewhere ? for people like me discovering this issue :) while being blocked also in recovery mode

**Comment by aguileraGit** [comment]
I'm having the same issue with 7.1. Help?

**Comment by hfrid** [comment]
Issue persists with 7.2. Help?

**Comment by drandreaskrueger** [comment]
Oh you poor people, problem is still there after >3 years. Sorry to read that. Leaving you now. Unsubscribed. Good luck.

**Comment by cgsecurity** [comment]
Please consult issue #65
