### ISSUE TITLE
Tagging releases and betas

### ISSUE THREAD

**Issue by HinTak** [cgsecurity/testdisk#84]
I see there are no git tags in the git repository . It is useful to have them especially for contributors and testers to identify whether some new functionality is in a release / beta or not.

For example, lately I like to know what has changed since 7.1 in the zip or jpeg area to evaluate whether to use a git build vs a release build.

**Comment by cgsecurity** [comment]
Fixed by "git push --tags"

**Comment by HinTak** [comment]
Thanks!
