### ISSUE TITLE
cannot recover partition under Windows (but recovered under Linux)

### ISSUE THREAD

**Issue by ibonobo** [cgsecurity/testdisk#85]
I have a Seagate removable 4TB drive, and the connection weakened, resulting in some corruption which was inadequately fixed. Long story short, I was able to use TestDisk under Linux and restore it, after having failed to do so under Windows (I think I chose the incorrect, older type of partition). It is still impossible to recover the partition and use the drive under Windows. Here is the error log under Windows: https://docs.google.com/document/d/1tGefpy679_rycbPG9-X9kf11K9R-q3J-30THoLC2j9A/edit?usp=sharing 

Please help. Thank you.

**Comment by cgsecurity** [comment]
The partition table lists your 4 TB partition. It seems OK.
Please read https://www.cgsecurity.org/testdisk.pdf the chapter about Repairing Filesystem.
If you need help, please go to https://forum.cgsecurity.org instead of opening a bug report.
