### ISSUE TITLE
Consider using XDG_CACHE_HOME for the log file

### ISSUE THREAD

**Issue by ZerdoX-x** [cgsecurity/testdisk#94]
This means instead of `$HOME/testdisk.log`, `$XDG_CACHE_HOME/testdisk/log` would be used.
If `$XDG_CACHE_HOME` is not set, the fallback `$HOME/.cache` should be substituted instead.

**Comment by cgsecurity** [comment]
testdisk.log is created in the current working directory, not in $HOME/testdisk.log. This behavior is wanted and also necessary when running several instances of testdisk in parallel.
